In [10]:
import numpy
n = numpy.arange(27)

In [5]:
type(n)

numpy.ndarray

In [6]:
print(n)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26]


In [7]:
n.reshape(3,9)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26]])

In [9]:
n.reshape(3,3,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [12]:
n2 = numpy.asarray([[1,2,3],[],[]])
n2

array([list([1, 2, 3]), list([]), list([])], dtype=object)

In [14]:
import cv2
im_g = cv2.imread("smallgray.png", 1)
im_g

array([[[187, 187, 187],
        [158, 158, 158],
        [104, 104, 104],
        [121, 121, 121],
        [143, 143, 143]],

       [[198, 198, 198],
        [125, 125, 125],
        [255, 255, 255],
        [255, 255, 255],
        [147, 147, 147]],

       [[209, 209, 209],
        [134, 134, 134],
        [255, 255, 255],
        [ 97,  97,  97],
        [182, 182, 182]]], dtype=uint8)

In [16]:
cv2.imwrite("newsmallgray.png", im_g)

True

In [25]:
im_g = cv2.imread("smallgray.png", 0)
im_g[1:3,0:2]

array([[198, 125],
       [209, 134]], dtype=uint8)

In [26]:
im_g.shape

(3, 5)

In [27]:
for row in im_g.T:
    print(row)

[187 198 209]
[158 125 134]
[104 255 255]
[121 255  97]
[143 147 182]


In [28]:
for i in im_g.flat:
    print(i)

187
158
104
121
143
198
125
255
255
147
209
134
255
97
182


In [31]:
ims = numpy.hstack((im_g, im_g))
print(ims)

[[187 158 104 121 143 187 158 104 121 143]
 [198 125 255 255 147 198 125 255 255 147]
 [209 134 255  97 182 209 134 255  97 182]]


In [32]:
ims = numpy.vstack((im_g, im_g))
print(ims)

[[187 158 104 121 143]
 [198 125 255 255 147]
 [209 134 255  97 182]
 [187 158 104 121 143]
 [198 125 255 255 147]
 [209 134 255  97 182]]


In [39]:
lst = numpy.hsplit(ims, 5)
print(lst)

[array([[187],
       [198],
       [209],
       [187],
       [198],
       [209]], dtype=uint8), array([[158],
       [125],
       [134],
       [158],
       [125],
       [134]], dtype=uint8), array([[104],
       [255],
       [255],
       [104],
       [255],
       [255]], dtype=uint8), array([[121],
       [255],
       [ 97],
       [121],
       [255],
       [ 97]], dtype=uint8), array([[143],
       [147],
       [182],
       [143],
       [147],
       [182]], dtype=uint8)]


In [42]:
lst = numpy.vsplit(ims, 3)
print(lst[0])

[[187 158 104 121 143]
 [198 125 255 255 147]]
